### PR TITLE
Remove role_tags from cisagov/terraform-state-read-role-tf-module configuration

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies the Terraform code to remove `role_tags` from the [cisagov/terraform-state-read-role-tf-module](https://github.com/cisagov/terraform-state-read-role-tf-module) configuration.

## 💭 Motivation and context ##

This is in accordance with the changes in cisagov/terraform-state-read-role-tf-module#5.

Note that `var.tags` is passed in via the provider's default tags, so there is no need to use `additional_role_tags` here.

## 🧪 Testing ##

I applied these changes to our COOL production and staging environments and verified that the only change that `terraform apply` wanted to apply was to add some tags to an extant IAM policy resource.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Do we want to also add the Workspace-exclusion foo here like we have elsewhere (e.g. https://github.com/cisagov/cool-userservices-dns/pull/6/commits/b86b7152e845d9d7d9c2818e7554859c084125a4?)

**Review by mcdonnnj — APPROVED** [review]
Are we not updating the `provisionterraform` provider to exclude the `Workspace` tag? We're doing similar in other PRs to remove the `role_tag` key.

**Comment by jsf9k** [comment]
> Are we not updating the `provisionterraform` provider to exclude the `Workspace` tag? We're doing similar in other PRs to remove the `role_tag` key.

See commit e69e239.

**Comment by jsf9k** [comment]
> Do we want to also add the Workspace-exclusion foo here like we have elsewhere (e.g. [cisagov/cool-userservices-dns@b86b715](https://github.com/cisagov/cool-userservices-dns/commit/b86b7152e845d9d7d9c2818e7554859c084125a4)?)

See commit e69e239.

**Review by mcdonnnj — APPROVED** [review]
✔✨ :shipit:

**Review by dav3r — APPROVED** [review]
🎸

**Pull request merged**
